### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by SethSterling** [SethSterling/MouseHouse#3]
The README should include

- Project description
- Coding convention guidelines
- How to run the project/prerequisites
- Screenshots of the developing website
- CI badge

**Comment by SpencerTSterling** [comment]
Include a section about the images folder in the **How to run the project**. 

A folder for products' images needs to be manually added to the wwwroot folder of the project in order to add new products to the database due to the product object's required field IFormFile Image. The folder _must_  be called "images" or else you will get a DirectoryNotFoundException. 
![image](https://user-images.githubusercontent.com/63821532/110405547-9d8fc880-8035-11eb-81db-23b5222c4d9e.png)

Add the folder _images_ to the wwwroot. 

![image](https://user-images.githubusercontent.com/63821532/110405851-1858e380-8036-11eb-87e3-773bc9f84bbb.png)

If there is an x symbol over the folder, it means the folder was not properly added to the project. You need to go through the File Explorer and add the folder in the wwwroot of the project from there. 

Right click the wwwroot folder and Open in File Explorer. 
Then add a new folder and name it _images_.
![image](https://user-images.githubusercontent.com/63821532/110406006-5bb35200-8036-11eb-913e-e4b1f56d8856.png)

![image](https://user-images.githubusercontent.com/63821532/110406265-ca90ab00-8036-11eb-8f49-ddfae9f42cf1.png)

When the images folder is properly added to the project, the x over the folder should be gone. 
![image](https://user-images.githubusercontent.com/63821532/110406396-03308480-8037-11eb-902b-8605e4c525b9.png)

**Comment by SpencerTSterling** [comment]
Dependencies used for this project:
- EntityFramework by Microsoft v6.4.4
- Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore by Microsoft v3.1.10
- Microsoft.AspNetCore.Identity.UI by Microsoft v3.1.10
- Microsoft.EntityFrameworkCore.Sqlite by Microsoft v3.1.11
- Microsoft.VisualStudio.Web.CodeGeneration.Design by Microsoft v3.1.5
- SendGrid by Elmer Thomas, Twilio DX Team v9.22.0
